#%RAML 1.0 NamedExample
value:
-
  id: 8
  portada: "ruta/imagen.png"
  titulo: "El laboratorio de Dexter"
  genero: "comedia"
  sinopsis: "Sigue las aventuras de Dexter, un niño genio que tiene su propio laboratorio secreto, donde crea increíbles inventos que a menudo le causan problemas con su hermana mayor Dee Dee y otros personajes"
  temporadas: 4
  capitulos: 78
  fecha_estreno: "1996-04-28"
  casa_animadora: "Cartoon Network Studios"
  creador: "Genndy Tartakovsky"
  calificacion_med: 4.4
-
  id: 9
  portada: "ruta/imagen.png"
  titulo: "Primal"
  genero: "aventuras"
  sinopsis: "Sigue las aventuras de un cavernícola y un tiranosaurio que se unen para sobrevivir en un mundo prehistórico hostil y violento, donde la muerte acecha en cada esquina"
  temporadas: 2
  capitulos: 15
  fecha_estreno: "2019-10-07"
  casa_animadora: "Cartoon Network Studios"
  creador: "Genndy Tartakovsky"
  calificacion_med: 4.8