#%RAML 1.0 NamedExample
value:
  - 
    id: 7
    portada: "ruta/imagen.png"
    titulo: "Final Space"
    genero: "aventuras"
    sinopsis: "Sigue las aventuras de Gary, un prisionero espacial que se hace amigo de Mooncake, un alienígena capaz de destruir planetas, y que intenta resolver el misterio del Final Space, una dimensión donde habitan los temibles Titanes"
    temporadas: 3
    capitulos: 36
    fecha_estreno: "2018-02-26"
    casa_animadora: "ShadowMachine"
    creador: "Olan Rogers"
    calificacion_med: 4.3
    resenas:
      - 
        id: 1
        id_caricatura: 7
        id_usuario: 123
        titulo: "Final Space"
        usuario: "usuario1"
        fecha: 2023-12-15T12:00:00Z
        resena: "¡Increíble!"
        calificacion: 5
        spoiler: false
      - 
        id: 2
        id_caricatura: 7
        id_usuario: 345
        titulo: "Final Space"
        usuario: "usuario2"
        fecha: 2023-12-15T12:00:00Z
        resena: "Me encantó, especialmente el final"
        calificacion: 5
        spoiler: true