#%RAML 1.0 NamedExample
value:
-
  id: 1
  portada: "ruta/imagen.png"
  titulo: "Hilda"
  genero: "aventuras"
  sinopsis: "Sigue las aventuras de Hilda, una niña de cabello azul que se muda de su bosque encantado a la ciudad deTrolberg, donde hace nuevos amigos y conoce a criaturas mágicas"
  temporadas: 3
  capitulos: 34
  fecha_estreno: "2018-08-21"
  casa_animadora: "Mercury Filmworks"
  creador: "Luke Pearson"
  calificacion_med: 4.8
-
  id: 6
  portada: "ruta/imagen.png"
  titulo: "Hora de Aventura"
  genero: "aventuras"
  sinopsis: "Sigue las aventuras de Finn, un niño valiente y curioso, y Jake, un perro con poderes mágicos, que viven en la Tierra de Ooo, un mundo lleno de personajes extraños y divertidos"
  temporadas: 10
  capitulos: 283
  fecha_estreno: "2010-04-05"
  casa_animadora: "Cartoon Network Studios"
  creador: "Pendleton Ward"
  calificacion_med: 4.7