#%RAML 1.0 NamedExample
value:
-
  id: 23
  id_caricatura: 30
  id_usuario: 400
  titulo: "Inside Job"
  usuario: "usuario13"
  fecha: 2023-12-15T12:00:00Z
  resena: "Una de las mejores que he visto"
  calificacion: 4.4
  spoiler: false