#%RAML 1.0 ResourceType

types:
  Caricatura:
    properties:
      id: number
      titulo: string
      genero: string
      sinopsis: string
      temporadas: number
      capitulos: number
      fecha_estreno: datetime
      calificacion_med: number
      casa_animadora: string
      creador: string
      portada: string
  Reseña:
    properties:
      id: number
      id_caricatura: Caricatura.id
      id_usuario: Usuario.id
      titulo: Caricatura.titulo
      portada: Caricatura.portada
      usuario: Usuario.nombre
      fecha: datetime
      reseña: string
      calificacion: number
      spoiler: boolean
  Usuario:
    properties:
      id: number
      nombre: string
      contraseña: password
      email: email