#%RAML 1.0 ResourceType

types:
  Caricatura:
    properties:
      titulo: string
      genero: string
      sinopsis: string
      temporadas: number
      capitulos: number
      fecha_estreno: datetime
      calificacion_med: number
      casa_animadora: string
      creador: string