#%RAML 1.0 DataType
displayName: Caricatura
description: Define el tipo de datos de Caricatura

type: object
properties:
  id: number
  portada: string
  titulo: string
  genero: string
  sinopsis: string
  temporadas: number
  capitulos: number
  fecha_estreno: string
  casa_animadora: string
  creador: string
  calificacion_med: number
  resenas?: Resena[] 